openapi: 3.0.0
info:
  title: Mock Data API
  description: API to fetch mock data with pagination
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/data:
    get:
      summary: Retrieve paginated mock data
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: Number of items per page (default 10)
        - in: query
          name: offset
          schema:
            type: integer
          description: Number of items to skip (default 0)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_count:
                    type: integer
                    description: Total count of mock data items
                  page_count:
                    type: integer
                    description: Total number of pages
                  page:
                    type: integer
                    description: Current page number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Unique identifier for the data item
                        name:
                          type: string
                          description: Name of the data item
                        description:
                          type: string
                          description: Description of the data item
                        slug:
                          type: string
                          description: Slugified version of the name
                        image:
                          type: string
                          description: URL of the image associated with the data item
      tags:
        - Mock Data
